New topo capabilities
gvallee/dpu_offload_service pull request #239
Opened 2023-01-18 21:48 UTC by gvallee

2023-01-23 23:24 UTC, bws commented on include/dpu_offload_group_cache.h
> +                                                  host_info_t *host_id);
This should be a size_t (an array index into the host array)

2023-01-25 18:23 UTC, gvallee commented on include/dpu_offload_group_cache.h
> +                                                  host_info_t *host_id);
Fixed

2023-01-25 21:04 UTC, bws requested changes

2023-01-25 21:07 UTC, bws commented on include/dpu_offload_group_cache.h
> +dpu_offload_status_t get_ordered_host_id_by_group(offloading_engine_t *engine,
This should be get_host_idx_by_group

2023-01-25 21:08 UTC, bws commented on include/dpu_offload_group_cache.h
> +dpu_offload_status_t get_num_sps_by_group_host(offloading_engine_t *engine,
this can be get_num_sps_by_group_host_idx

2023-01-25 21:10 UTC, bws commented on include/dpu_offload_group_cache.h
> +dpu_offload_status_t get_num_ranks_for_group_host(offloading_engine_t *engine,
could be get_num_ranks_for_group_host_idx

2023-01-25 21:11 UTC, bws commented on include/dpu_offload_group_cache.h
> +dpu_offload_status_t get_n_for_rank_by_group_host(offloading_engine_t *engine,
get_rank_idx_by_group_host_idx

2023-01-25 21:11 UTC, bws commented on include/dpu_offload_group_cache.h
> +dpu_offload_status_t get_all_sps_by_group_host(offloading_engine_t *engine,
get_all_sps_by_group_host_idx

2023-01-25 21:13 UTC, bws commented on include/dpu_offload_group_cache.h
> +dpu_offload_status_t get_nth_sp_by_group_host(offloading_engine_t *engine,
get_local_sp_idx_by_group_host_idx

2023-02-02 16:58 UTC, bws commented on include/dpu_offload_group_cache.h
> +dpu_offload_status_t get_all_ranks_by_group_sp(offloading_engine_t *engine,
I realize I need this to be a host_idx with a local sp_id rather than a global sp_id

2023-02-05 17:09 UTC, merged